Watching for file changes with StatReloader
Waiting for apps ready_event.
Apps ready_event triggered. Sending autoreload_started signal.
Watching dir E:\DjangoProject\my_blog\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\contrib\admin\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\contrib\auth\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\contrib\contenttypes\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\contrib\sessions\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\contrib\messages\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\contrib\staticfiles\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\contrib\sites\locale with glob **/*.mo.
Watching dir E:\DjangoProject\my_blog\article\locale with glob **/*.mo.
Watching dir E:\DjangoProject\my_blog\userprofile\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\password_reset\locale with glob **/*.mo.
Watching dir E:\DjangoProject\my_blog\comment\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\taggit\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\ckeditor\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\mptt\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\notifications\locale with glob **/*.mo.
Watching dir E:\DjangoProject\my_blog\notice\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\allauth\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\allauth\account\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\allauth\socialaccount\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\allauth\socialaccount\providers\weixin\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\allauth\socialaccount\providers\weibo\locale with glob **/*.mo.
Watching dir C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\allauth\socialaccount\providers\github\locale with glob **/*.mo.
(0.001) b'SELECT @@SQL_AUTO_IS_NULL'; args=None
(0.001) b'SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED'; args=None
(0.512) b'SHOW FULL TABLES'; args=None
(0.003) b'SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`'; args=()
File E:\DjangoProject\my_blog\my_blog\settings.py. is_changed: False, is_new: True
File E:\DjangoProject\my_blog\my_blog\settings.py previous mtime: None, current mtime: 1584704598.2750716
E:\DjangoProject\my_blog\my_blog\settings.py notified as changed. Signal results: [(<function translation_file_changed at 0x000001A7934D4A60>, None)].
E:\DjangoProject\my_blog\my_blog\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /notice/list/ HTTP/1.1" 302 0
"GET /userprofile/login/?next=/notice/list/ HTTP/1.1" 200 5667
E:\DjangoProject\my_blog\my_blog\settings.py changed, reloading.
"GET /userprofile/login/?next=/notice/list/888 HTTP/1.1" 500 59
"GET /userprofile/login/?next=/notice/list/888 HTTP/1.1" 500 59
"GET /userprofile/login/?next=/notice/list/888 HTTP/1.1" 500 59
Internal Server Error: /article/article_detail/888/
Traceback (most recent call last):
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DjangoProject\my_blog\article\views.py", line 69, in article_detail
    article = Article.objects.get(id=id)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\models\query.py", line 408, in get
    self.model._meta.object_name
article.models.Article.DoesNotExist: Article matching query does not exist.
"GET /article/article_detail/888/ HTTP/1.1" 500 78446
ERROR 2020-03-20 22:18:38,865 log 1324 4744 Internal Server Error: /article/article_list/
Traceback (most recent call last):
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'my_filters_and_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DjangoProject\my_blog\article\views.py", line 63, in article_list
    return render(request, 'article/list.html', context)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 1025, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'my_filters_and_tags' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
mptt_admin
mptt_tags
notifications_tags
socialaccount
static
staticfiles
tz
ERROR 2020-03-20 22:18:45,849 log 1324 11064 Internal Server Error: /article/article_list/
Traceback (most recent call last):
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'my_filters_and_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DjangoProject\my_blog\article\views.py", line 63, in article_list
    return render(request, 'article/list.html', context)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 1025, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'my_filters_and_tags' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
mptt_admin
mptt_tags
notifications_tags
socialaccount
static
staticfiles
tz
ERROR 2020-03-20 22:19:46,250 log 1324 9120 Internal Server Error: /article/article_list/
Traceback (most recent call last):
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'my_filters_and_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DjangoProject\my_blog\article\views.py", line 63, in article_list
    return render(request, 'article/list.html', context)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 1025, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'my_filters_and_tags' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
mptt_admin
mptt_tags
notifications_tags
socialaccount
static
staticfiles
tz
ERROR 2020-03-20 22:38:19,260 log 11712 8100 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DjangoProject\my_blog\article\views.py", line 63, in article_list
    return render(request, 'article/list.html', context)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\hou\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ': 'Y-m-d'' from 'article.created|date: 'Y-m-d''
